steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/payments-microservice',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/microservices-dev-459902/images-registry/payments-microservice',
    ]
options:
  logging: CLOUD_LOGGING_ONLY
